version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      GfUZul/CQf5K8qlxRaacYF3liLdTZIYrgeaQ/Fc5sqbk9bJ3m/mlvO4xgFUvlHhj7AqmzSFpY1bg0TZQU9FZPRtZGMMdKjtoOP0HOrourWvmh5h5rqlY35B2kU31DJJz/BkcpVAWMJGDdkzAJwrSNIGIDlYrnjO155WIQbmVKG44x/BU7EfQnMpnPKlj+PkT+iLMDtLXFCl8ehJlJzstjwTKCrYS/RKO4RWjPRMZQZcNAsaPh3w3ursQRJ8Tprdn1MpkhXLlXqctQ3+bb+cxxSYOQIOmtpeWf9eiPl+HmQQCPHe9DI5cuBf5XU4z+idWH4aXUusACir4TM9VEHWtqbH7vYv+TJRy+SD0gth8jiKWpPYeeZ6W2JHTDVFZCYkyMXbHOj1rHyl0BeitL+hfeyziNwP7KzRjOF5Xuf7IgKCjeazS9pqxhIVuXK5o8heTL5hx6nqJ19MNqVfbHdtktQoj1Htgo4UYtiDHUnX2myZgHWFpyq+9EYJVDj67mL0/pMrlJeJ1OdDiCXCVaAy9QT+QVqXWQZIlBTS6U+t6XWFX1492uzHN9SmgcQ/I7f8R0mV1tgdjlDAhGbFstOBDuHlWpCSMmG+qwcSRdr9I9cW4HAbFRNupUKocDhMw0qMEWLX7b2LEp1wJmuIgSKzWahYf4R2OTp3CwVQKz18Np8E=
