version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      gHfpH8jPVcthEN3SVoUsTr9v10nsg5D5x86qFbpQYfhy1ZAEhcEocgJZ53E4UuYxypeFNfQ1gRDmXQePvoItyjLw+dHa/Ikq1ZMO5VNxB61fZqAWuVJnOQLnZC/PYpYqzfH/Jwbcz4FwQMAh8eJmICyhzWEJ05lFXZVA3UnKCCfP4wZmUGslZfPKo7+vLYh1Wy/Y+/V9y4ln+Pg733aOkJYjOW4mRTvH6qnHAaww74QoSiJ44qjvz4wIsSzVN0kp6cn4SJuM6w41MhPZjBCQCV6/JZcR1dANO6Q75wKnFXKfkFipcCzvlronvOfQUeBdJkGQUUkHTAxOgYjBVnHzS+YyitxnlaUvCiJV838L312LAA8VO8cktgCsp8/XO/ggD4smDTdrasJIbziFxGpJI3mebW3fHq8X0ZY6Nlv65C4aKZ8dUIsysuBvmqMaX+xw2XPe4FRR+G1zQPIaepCSUvw8+oIThDvYXm/wAICzCFiXYMG0bbWaGzUqwTryT8WOye7y3JOaoxxbK2tqq3cUThCQsADMQRf3wd0P92nFfs+IpWpM+pdg6iUg4LUFk/SaEYBHzIuCjVkyJ/UtQ36WapQuMJqOf2YXNG/lZfRdQEWj+Q518Ok0qTx8cBm911fgKmjKomH8t+ktcsmzmsPAAhUbaldhGkgy18TO9JD2Cj4=
