version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      YF1FhzV5/N5aYWqL8zE7Y4ATpt1nHBqNmoqWd5YGIZToNr8WxVDxhtBhMemxhLJXd7pJOF8e+ikQ0Cb6ZXi9fycSkPxsujK3eH8YDfyjm/Wp/BjqC+jQsFqW2DCZ37MKu0k8GRQMXJ/4DasGNfjXRA7m9Cxfvbr3AS8i3A5vSloM8zl/cj0CGbU/NuaJrDSbKzaY1ntUYLm5jn77zV7jkLtE+Mr7bAj0P7U8WLaY1erCt8P5VrtN2vAyj6GE6A0Yr5qGCJ+teDR1B8ll7THbWZ6snmQH8DPourvuNVK1GJ+TEh8CIPPNnvbO/tYsGQQtPSSup8cXTuvTXX+Hy7SjQJw2ai2pSmhgRYAJRq8ksMPAAIUSgKL66dl/oFRDHNIFOPz0g+AMc5tlX6IbzeSFo2l/5E5NelUcXXRU513gJhSD+Dib6rqmb39hJ59LyeoIpEetkZ7cGeVdPMm+TPF93F44cn74C4x2QDsiGJNkeE4PKl3MdCEn5wOw1OhM/Fl582jWe2IFKJ21kxqrhc3pbzg6KWetuVSzwY+NIL8Uv2SvL9jxid3wbphcZ2uU4JXH+E+FcwXYTqS7zmcF/eOGSF9PqHOzPqzLbZQ8dtWxhmFTiAD1i0Nw7NU/5eLWai7kkIwkQA5D2aXzxAXHcLFEzcih/PZcSCkTz1bAMKOjfJM=
