sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: Il/zhi8Cqc390GWoqzz67nZxBCjw2PhgbmrvRGk5FuWqAbGj8de9VfYcBkm9iAlNX1zl0Deis3KI8J2qoli21/WozveWo9bYGAkPn0ZBqxcTXXNCxe5NI541SRGUqdBDdM/ss9s1jlcMWq+/KxfXXGumJnG/lzooTMTc053lDjn7AQlTma7AJ+M2oRAwv2dzeL5WdcXlhi3XSQu9oJOZz5lIhpVg2wQFrnMj8JSJxWo9w6zI0ZwfFR7jjnYFomKaIW8rwv4qW9Ws89NSLH+il3T0HhT1o8ZhlOID/6IpArNwDerIHzTcUcpkFny3g8ExOVNht0IElCGbfWMP9PKJRPy7X7uuNMOi9IqkuzESYQ9pPzKlQtIjNHcuuoEkfj/999k+mbz8zWj1XNIbMCE47xPw4++xTKcM5gaC9rLD/sMrDrnf+Fj94oiFrGPtd0YmNqMb12scS9LLUqB0Smot9D91bEGmkMjIotFGECCCihpI4BewiZsjHQjOSoPTXT+1D4yDRZqIx/bFtzazGIiHwEgJURCMx3rZr83q6GE6iGiH6lIhFBDCfpHEOSHx9E2gfPQ6m4CAIEcR8beUxsHaBbqu2H3VUIC8hXIp/CWWSi6nNsyUXMlffjeEPlL4EuaITzotOITTLcWWMoNyJT/pXAZURESi/NZahrrpHfgYjiI=
