on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest]
        node: [10, 12, 14, 15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install desired Node.js version for compilation
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - run: npm run our:setup
      - run: npm run our:compile
      - run: npm run our:verify

      - name: Install targeted Node.js version for testing
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - run: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    if: ${{ github.event_name == 'push' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install desired Node.js version for publishing
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - run: npm run our:setup
      - run: npm run our:compile
      - run: npm run our:meta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish to npm
        uses: bevry-actions/npm@v1.0.0
        with:
          npmAuthToken: ${{secrets.NPM_AUTHTOKEN}}
          npmBranchTag: 'master:next'

      - name: publish to surge
        uses: bevry-actions/surge@v1.0.3
        with:
          surgeLogin: ${{secrets.SURGE_LOGIN}}
          surgeToken: ${{secrets.SURGE_TOKEN}}
